#  ---------------------------------------------------------------------
# Pin assign --
#  ---------------------------------------------------------------------

# System ---------------------------------------------------------------
set_property PACKAGE_PIN L23 [get_ports PROGB_ON]
set_property PACKAGE_PIN AC18 [get_ports BASE_CLKP]
set_property PACKAGE_PIN AD18 [get_ports BASE_CLKN]
set_property PACKAGE_PIN W24 [get_ports USR_RSTB]
set_property PACKAGE_PIN U5 [get_ports {DIP[1]}]
set_property PACKAGE_PIN U6 [get_ports {DIP[2]}]
set_property PACKAGE_PIN U2 [get_ports {DIP[3]}]
set_property PACKAGE_PIN U1 [get_ports {DIP[4]}]
set_property PACKAGE_PIN N12 [get_ports VP]
set_property PACKAGE_PIN P11 [get_ports VN]

# GTX ------------------------------------------------------------------
set_property PACKAGE_PIN D6 [get_ports GTX_REFCLK_P]
set_property PACKAGE_PIN D5 [get_ports GTX_REFCLK_N]
#set_property PACKAGE_PIN F2 [get_ports GTX_TX_P]
#set_property PACKAGE_PIN G4 [get_ports GTX_RX_P]
#set_property PACKAGE_PIN F1 [get_ports GTX_TX_N]
#set_property PACKAGE_PIN G3 [get_ports GTX_RX_N]

# SPI flash ------------------------------------------------------------
set_property PACKAGE_PIN B24 [get_ports MOSI]
set_property PACKAGE_PIN A25 [get_ports DIN]
set_property PACKAGE_PIN C23 [get_ports FCSB]

# MIKUMARI -------------------------------------------------------------
set_property PACKAGE_PIN AF14 [get_ports MIKUMARI_TXP]
set_property PACKAGE_PIN AF15 [get_ports MIKUMARI_TXN]
set_property PACKAGE_PIN AB16 [get_ports MIKUMARI_RXP]
set_property PACKAGE_PIN AC16 [get_ports MIKUMARI_RXN]

# EEPROM ---------------------------------------------------------------
set_property PACKAGE_PIN AB22 [get_ports EEP_CS]
set_property PACKAGE_PIN AC22 [get_ports EEP_SK]
set_property PACKAGE_PIN AB21 [get_ports EEP_DI]
set_property PACKAGE_PIN AC21 [get_ports EEP_DO]

# MPPC-BIAS ------------------------------------------------------------
set_property PACKAGE_PIN AD25 [get_ports BIAS_CSB]
set_property PACKAGE_PIN AE25 [get_ports BIAS_SCLK]
set_property PACKAGE_PIN AE22 [get_ports BIAS_DIN]
set_property PACKAGE_PIN AE23 [get_ports BIAS_CLB]

# NIM-IO ---------------------------------------------------------------
set_property PACKAGE_PIN AD16 [get_ports {NIM_IN[1]}]
set_property PACKAGE_PIN AE16 [get_ports {NIM_IN[2]}]
set_property PACKAGE_PIN AB17 [get_ports {NIM_OUT[1]}]
set_property PACKAGE_PIN AC17 [get_ports {NIM_OUT[2]}]

# JItter cleaner -------------------------------------------------------
set_property PACKAGE_PIN AF24 [get_ports CDCE_PDB]
set_property PACKAGE_PIN AF25 [get_ports CDCE_LOCK]
set_property PACKAGE_PIN AF23 [get_ports CDCE_SCLK]
set_property PACKAGE_PIN AF22 [get_ports CDCE_SO]
set_property PACKAGE_PIN AE26 [get_ports CDCE_SI]
set_property PACKAGE_PIN AD26 [get_ports CDCE_LE]
set_property PACKAGE_PIN AF19 [get_ports CDCE_REFP]
set_property PACKAGE_PIN AF20 [get_ports CDCE_REFN]

set_property PACKAGE_PIN AA10 [get_ports CLK_FASTP]
set_property PACKAGE_PIN AB10 [get_ports CLK_FASTN]
set_property PACKAGE_PIN AB11 [get_ports CLK_SLOWP]
set_property PACKAGE_PIN AC11 [get_ports CLK_SLOWN]

#set_property PACKAGE_PIN AA10 [get_ports MIGS_CLKP]
#set_property PACKAGE_PIN AB10 [get_ports MIGS_CLKN]
#set_property PACKAGE_PIN AB11 [get_ports TDC_CLKP]
#set_property PACKAGE_PIN AC11 [get_ports TDC_CLKN]

# Test pins ------------------------------------------------------------
set_property PACKAGE_PIN Y22 [get_ports {TESTPIN[1]}]
set_property PACKAGE_PIN AA22 [get_ports {TESTPIN[2]}]
set_property PACKAGE_PIN AC23 [get_ports {TESTPIN[3]}]
set_property PACKAGE_PIN W20 [get_ports {TESTPIN[4]}]

# CITIROC pins ---------------------------------------------------------
set_property PACKAGE_PIN N23 [get_ports CI_PWRON]
set_property PACKAGE_PIN P23 [get_ports CI_RSTB_PA]
set_property PACKAGE_PIN R23 [get_ports CI_RSTB_SR]
set_property PACKAGE_PIN T24 [get_ports CI_RSTB_READ]
set_property PACKAGE_PIN T22 [get_ports CI_RSTB_PSC]

set_property PACKAGE_PIN M24 [get_ports CI_SRIN]
set_property PACKAGE_PIN T23 [get_ports CI_READIN]
set_property PACKAGE_PIN M22 [get_ports CI_CLK_SR]
set_property PACKAGE_PIN N26 [get_ports CI_CLK_READ]
set_property PACKAGE_PIN M26 [get_ports CI_LOAD_SC]
set_property PACKAGE_PIN N22 [get_ports CI_SELECT]
set_property PACKAGE_PIN P25 [get_ports CI_SROUT]
set_property PACKAGE_PIN N24 [get_ports CI_READOUT]

set_property PACKAGE_PIN U25 [get_ports CI_HOLD_HG]
set_property PACKAGE_PIN T25 [get_ports CI_HOLD_LG]
set_property PACKAGE_PIN L25 [get_ports CI_MODEB_EXT]
set_property PACKAGE_PIN M20 [get_ports CI_PS_GTRIG]
set_property PACKAGE_PIN M19 [get_ports CI_VEVT]
set_property PACKAGE_PIN N21 [get_ports CI_RAZCHN]

set_property PACKAGE_PIN T20 [get_ports {PMUX_A[0]}]
set_property PACKAGE_PIN R20 [get_ports {PMUX_A[1]}]

# CITIROC trigger ------------------------------------------------------
set_property PACKAGE_PIN G21 [get_ports {CI_TRIGB[1]}]
set_property PACKAGE_PIN H23 [get_ports {CI_TRIGB[2]}]
set_property PACKAGE_PIN E23 [get_ports {CI_TRIGB[3]}]
set_property PACKAGE_PIN L22 [get_ports {CI_TRIGB[4]}]
set_property PACKAGE_PIN K23 [get_ports {CI_TRIGB[5]}]
set_property PACKAGE_PIN K21 [get_ports {CI_TRIGB[6]}]
set_property PACKAGE_PIN J23 [get_ports {CI_TRIGB[7]}]
set_property PACKAGE_PIN K22 [get_ports {CI_TRIGB[8]}]
set_property PACKAGE_PIN H22 [get_ports {CI_TRIGB[9]}]
set_property PACKAGE_PIN J21 [get_ports {CI_TRIGB[10]}]
set_property PACKAGE_PIN G22 [get_ports {CI_TRIGB[11]}]
set_property PACKAGE_PIN H21 [get_ports {CI_TRIGB[12]}]
set_property PACKAGE_PIN F22 [get_ports {CI_TRIGB[13]}]
set_property PACKAGE_PIN E22 [get_ports {CI_TRIGB[14]}]
set_property PACKAGE_PIN J25 [get_ports {CI_TRIGB[15]}]
set_property PACKAGE_PIN D24 [get_ports {CI_TRIGB[16]}]
set_property PACKAGE_PIN J26 [get_ports {CI_TRIGB[17]}]
set_property PACKAGE_PIN D23 [get_ports {CI_TRIGB[18]}]
set_property PACKAGE_PIN H26 [get_ports {CI_TRIGB[19]}]
set_property PACKAGE_PIN H24 [get_ports {CI_TRIGB[20]}]
set_property PACKAGE_PIN G24 [get_ports {CI_TRIGB[21]}]
set_property PACKAGE_PIN G26 [get_ports {CI_TRIGB[22]}]
set_property PACKAGE_PIN G25 [get_ports {CI_TRIGB[23]}]
set_property PACKAGE_PIN F24 [get_ports {CI_TRIGB[24]}]
set_property PACKAGE_PIN F25 [get_ports {CI_TRIGB[25]}]
set_property PACKAGE_PIN F23 [get_ports {CI_TRIGB[26]}]
set_property PACKAGE_PIN E26 [get_ports {CI_TRIGB[27]}]
set_property PACKAGE_PIN E25 [get_ports {CI_TRIGB[28]}]
set_property PACKAGE_PIN D25 [get_ports {CI_TRIGB[29]}]
set_property PACKAGE_PIN J24 [get_ports {CI_TRIGB[30]}]
set_property PACKAGE_PIN D26 [get_ports {CI_TRIGB[31]}]
set_property PACKAGE_PIN E21 [get_ports {CI_TRIGB[32]}]
set_property PACKAGE_PIN D21 [get_ports {CI_TRIGB[33]}]
set_property PACKAGE_PIN C22 [get_ports {CI_TRIGB[34]}]
set_property PACKAGE_PIN A20 [get_ports {CI_TRIGB[35]}]
set_property PACKAGE_PIN C26 [get_ports {CI_TRIGB[36]}]
set_property PACKAGE_PIN B26 [get_ports {CI_TRIGB[37]}]
set_property PACKAGE_PIN C24 [get_ports {CI_TRIGB[38]}]
set_property PACKAGE_PIN A24 [get_ports {CI_TRIGB[39]}]
set_property PACKAGE_PIN A23 [get_ports {CI_TRIGB[40]}]
set_property PACKAGE_PIN C21 [get_ports {CI_TRIGB[41]}]
set_property PACKAGE_PIN B21 [get_ports {CI_TRIGB[42]}]
set_property PACKAGE_PIN B20 [get_ports {CI_TRIGB[43]}]
set_property PACKAGE_PIN G20 [get_ports {CI_TRIGB[44]}]
set_property PACKAGE_PIN F20 [get_ports {CI_TRIGB[45]}]
set_property PACKAGE_PIN D18 [get_ports {CI_TRIGB[46]}]
set_property PACKAGE_PIN D20 [get_ports {CI_TRIGB[47]}]
set_property PACKAGE_PIN H19 [get_ports {CI_TRIGB[48]}]
set_property PACKAGE_PIN F19 [get_ports {CI_TRIGB[49]}]
set_property PACKAGE_PIN H18 [get_ports {CI_TRIGB[50]}]
set_property PACKAGE_PIN F17 [get_ports {CI_TRIGB[51]}]
set_property PACKAGE_PIN F18 [get_ports {CI_TRIGB[52]}]
set_property PACKAGE_PIN K16 [get_ports {CI_TRIGB[53]}]
set_property PACKAGE_PIN G16 [get_ports {CI_TRIGB[54]}]
set_property PACKAGE_PIN J16 [get_ports {CI_TRIGB[55]}]
set_property PACKAGE_PIN F15 [get_ports {CI_TRIGB[56]}]
set_property PACKAGE_PIN L20 [get_ports {CI_TRIGB[57]}]
set_property PACKAGE_PIN J18 [get_ports {CI_TRIGB[58]}]
set_property PACKAGE_PIN K17 [get_ports {CI_TRIGB[59]}]
set_property PACKAGE_PIN E18 [get_ports {CI_TRIGB[60]}]
set_property PACKAGE_PIN H17 [get_ports {CI_TRIGB[61]}]
set_property PACKAGE_PIN L19 [get_ports {CI_TRIGB[62]}]
set_property PACKAGE_PIN G17 [get_ports {CI_TRIGB[63]}]
set_property PACKAGE_PIN J20 [get_ports {CI_TRIGB[64]}]
set_property PACKAGE_PIN D16 [get_ports {CI_TRIGB[65]}]
set_property PACKAGE_PIN D15 [get_ports {CI_TRIGB[66]}]
set_property PACKAGE_PIN E16 [get_ports {CI_TRIGB[67]}]
set_property PACKAGE_PIN C19 [get_ports {CI_TRIGB[68]}]
set_property PACKAGE_PIN B19 [get_ports {CI_TRIGB[69]}]
set_property PACKAGE_PIN A19 [get_ports {CI_TRIGB[70]}]
set_property PACKAGE_PIN A18 [get_ports {CI_TRIGB[71]}]
set_property PACKAGE_PIN C18 [get_ports {CI_TRIGB[72]}]
set_property PACKAGE_PIN B17 [get_ports {CI_TRIGB[73]}]
set_property PACKAGE_PIN A17 [get_ports {CI_TRIGB[74]}]
set_property PACKAGE_PIN C17 [get_ports {CI_TRIGB[75]}]
set_property PACKAGE_PIN B16 [get_ports {CI_TRIGB[76]}]
set_property PACKAGE_PIN C16 [get_ports {CI_TRIGB[77]}]
set_property PACKAGE_PIN E17 [get_ports {CI_TRIGB[78]}]
set_property PACKAGE_PIN F13 [get_ports {CI_TRIGB[79]}]
set_property PACKAGE_PIN G11 [get_ports {CI_TRIGB[80]}]
set_property PACKAGE_PIN H14 [get_ports {CI_TRIGB[81]}]
set_property PACKAGE_PIN J11 [get_ports {CI_TRIGB[82]}]
set_property PACKAGE_PIN J13 [get_ports {CI_TRIGB[83]}]
set_property PACKAGE_PIN J10 [get_ports {CI_TRIGB[84]}]
set_property PACKAGE_PIN J8 [get_ports {CI_TRIGB[85]}]
set_property PACKAGE_PIN G14 [get_ports {CI_TRIGB[86]}]
set_property PACKAGE_PIN J14 [get_ports {CI_TRIGB[87]}]
set_property PACKAGE_PIN H12 [get_ports {CI_TRIGB[88]}]
set_property PACKAGE_PIN H13 [get_ports {CI_TRIGB[89]}]
set_property PACKAGE_PIN G10 [get_ports {CI_TRIGB[90]}]
set_property PACKAGE_PIN F10 [get_ports {CI_TRIGB[91]}]
set_property PACKAGE_PIN H9 [get_ports {CI_TRIGB[92]}]
set_property PACKAGE_PIN G9 [get_ports {CI_TRIGB[93]}]
set_property PACKAGE_PIN E12 [get_ports {CI_TRIGB[94]}]
set_property PACKAGE_PIN H8 [get_ports {CI_TRIGB[95]}]
set_property PACKAGE_PIN H11 [get_ports {CI_TRIGB[96]}]
set_property PACKAGE_PIN F12 [get_ports {CI_TRIGB[97]}]
set_property PACKAGE_PIN E11 [get_ports {CI_TRIGB[98]}]
set_property PACKAGE_PIN G12 [get_ports {CI_TRIGB[99]}]
set_property PACKAGE_PIN D11 [get_ports {CI_TRIGB[100]}]
set_property PACKAGE_PIN D10 [get_ports {CI_TRIGB[101]}]
set_property PACKAGE_PIN E10 [get_ports {CI_TRIGB[102]}]
set_property PACKAGE_PIN F9 [get_ports {CI_TRIGB[103]}]
set_property PACKAGE_PIN D9 [get_ports {CI_TRIGB[104]}]
set_property PACKAGE_PIN D8 [get_ports {CI_TRIGB[105]}]
set_property PACKAGE_PIN A15 [get_ports {CI_TRIGB[106]}]
set_property PACKAGE_PIN B15 [get_ports {CI_TRIGB[107]}]
set_property PACKAGE_PIN B14 [get_ports {CI_TRIGB[108]}]
set_property PACKAGE_PIN A14 [get_ports {CI_TRIGB[109]}]
set_property PACKAGE_PIN D13 [get_ports {CI_TRIGB[110]}]
set_property PACKAGE_PIN C14 [get_ports {CI_TRIGB[111]}]
set_property PACKAGE_PIN E13 [get_ports {CI_TRIGB[112]}]
set_property PACKAGE_PIN C13 [get_ports {CI_TRIGB[113]}]
set_property PACKAGE_PIN D14 [get_ports {CI_TRIGB[114]}]
set_property PACKAGE_PIN A13 [get_ports {CI_TRIGB[115]}]
set_property PACKAGE_PIN A12 [get_ports {CI_TRIGB[116]}]
set_property PACKAGE_PIN B12 [get_ports {CI_TRIGB[117]}]
set_property PACKAGE_PIN C12 [get_ports {CI_TRIGB[118]}]
set_property PACKAGE_PIN B11 [get_ports {CI_TRIGB[119]}]
set_property PACKAGE_PIN C11 [get_ports {CI_TRIGB[120]}]
set_property PACKAGE_PIN A10 [get_ports {CI_TRIGB[121]}]
set_property PACKAGE_PIN B10 [get_ports {CI_TRIGB[122]}]
set_property PACKAGE_PIN B9 [get_ports {CI_TRIGB[123]}]
set_property PACKAGE_PIN A9 [get_ports {CI_TRIGB[124]}]
set_property PACKAGE_PIN C9 [get_ports {CI_TRIGB[125]}]
set_property PACKAGE_PIN F8 [get_ports {CI_TRIGB[126]}]
set_property PACKAGE_PIN A8 [get_ports {CI_TRIGB[127]}]
set_property PACKAGE_PIN F14 [get_ports {CI_TRIGB[128]}]

# DDR3 SDRAM -----------------------------------------------------------

# AD9220 ---------------------------------------------------------------
set_property PACKAGE_PIN AD23 [get_ports ADC_OTR]
set_property PACKAGE_PIN AD24 [get_ports ADC_BIT[1]]
set_property PACKAGE_PIN AC24 [get_ports ADC_BIT[2]]
set_property PACKAGE_PIN AC26 [get_ports ADC_BIT[3]]
set_property PACKAGE_PIN AB24 [get_ports ADC_BIT[4]]
set_property PACKAGE_PIN AB25 [get_ports ADC_BIT[5]]
set_property PACKAGE_PIN AB26 [get_ports ADC_BIT[6]]
set_property PACKAGE_PIN AA24 [get_ports ADC_BIT[7]]
set_property PACKAGE_PIN AA25 [get_ports ADC_BIT[8]]
set_property PACKAGE_PIN Y25 [get_ports ADC_BIT[9]]
set_property PACKAGE_PIN Y26 [get_ports ADC_BIT[10]]
set_property PACKAGE_PIN W25 [get_ports ADC_BIT[11]]
set_property PACKAGE_PIN W26 [get_ports ADC_BIT[12]]
set_property PACKAGE_PIN V26 [get_ports ADC_CLK]

#  ---------------------------------------------------------------------
# Port attribute --
#  ---------------------------------------------------------------------

# System ---------------------------------------------------------------
set_property IOSTANDARD LVCMOS18 [get_ports PROGB_ON]
set_property IOSTANDARD LVDS [get_ports BASE_CLKP]
set_property DIFF_TERM TRUE [get_ports BASE_CLKP]
set_property DIFF_TERM TRUE [get_ports BASE_CLKN]
set_property IOSTANDARD LVCMOS33 [get_ports USR_RSTB]
set_property IOSTANDARD LVCMOS15 [get_ports {DIP[*]}]
set_property PULLUP true [get_ports {DIP[4]}]
set_property PULLUP true [get_ports {DIP[3]}]
set_property PULLUP true [get_ports {DIP[2]}]
set_property PULLUP true [get_ports {DIP[1]}]

# GTX ------------------------------------------------------------------

# SPI flash ------------------------------------------------------------
set_property IOSTANDARD LVCMOS18 [get_ports MOSI]
set_property IOB TRUE [get_ports MOSI]
set_property IOSTANDARD LVCMOS18 [get_ports DIN]
set_property IOB TRUE [get_ports DIN]
set_property IOSTANDARD LVCMOS18 [get_ports FCSB]
set_property IOB TRUE [get_ports FCSB]

# MIKUMARI -------------------------------------------------------------
set_property IOSTANDARD LVDS [get_ports MIKUMARI_TXP]
set_property IOSTANDARD LVDS [get_ports MIKUMARI_RXP]
set_property DIFF_TERM TRUE [get_ports MIKUMARI_RXP]

# EEPROM ---------------------------------------------------------------
set_property IOSTANDARD LVCMOS33 [get_ports EEP_CS]
set_property IOSTANDARD LVCMOS33 [get_ports EEP_SK]
set_property IOSTANDARD LVCMOS33 [get_ports EEP_DI]
set_property IOSTANDARD LVCMOS33 [get_ports EEP_DO]

# MPPC-BIAS ------------------------------------------------------------
set_property IOSTANDARD LVCMOS33 [get_ports BIAS_CSB]
set_property IOSTANDARD LVCMOS33 [get_ports BIAS_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports BIAS_DIN]
set_property IOSTANDARD LVCMOS33 [get_ports BIAS_CLB]

# NIM-IO ---------------------------------------------------------------
set_property IOSTANDARD LVCMOS18 [get_ports {NIM_IN[*]}]
set_property IOSTANDARD LVCMOS18 [get_ports {NIM_OUT[*]}]
set_property IOB TRUE [get_ports NIM_OUT[2]]

# JItter cleaner -------------------------------------------------------
set_property IOSTANDARD LVCMOS33 [get_ports CDCE_PDB]
set_property IOSTANDARD LVCMOS33 [get_ports CDCE_LOCK]
set_property IOSTANDARD LVCMOS33 [get_ports CDCE_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports CDCE_SO]
set_property IOSTANDARD LVCMOS33 [get_ports CDCE_SI]
set_property IOSTANDARD LVCMOS33 [get_ports CDCE_LE]
set_property IOSTANDARD LVDS [get_ports CDCE_REFP]
set_property IOSTANDARD LVDS [get_ports CDCE_REFN]

set_property IOSTANDARD LVDS [get_ports CLK_FASTP]
set_property IOSTANDARD LVDS [get_ports CLK_FASTN]
set_property IOSTANDARD LVDS [get_ports CLK_SLOWP]
set_property IOSTANDARD LVDS [get_ports CLK_SLOWN]

#set_property IOSTANDARD LVDS [get_ports MIGS_CLKP]
#set_property IOSTANDARD LVDS [get_ports TDC_CLKP]


# Test pins ------------------------------------------------------------
set_property IOSTANDARD LVCMOS33 [get_ports {TESTPIN[*]}]

# CITIROC pins ---------------------------------------------------------
set_property IOSTANDARD LVCMOS33 [get_ports CI_PWRON]
set_property IOSTANDARD LVCMOS33 [get_ports CI_RSTB_PA]
set_property IOSTANDARD LVCMOS33 [get_ports CI_RSTB_SR]
set_property IOSTANDARD LVCMOS33 [get_ports CI_RSTB_READ]
set_property IOSTANDARD LVCMOS33 [get_ports CI_RSTB_PSC]

set_property IOSTANDARD LVCMOS33 [get_ports CI_SRIN]
set_property IOSTANDARD LVCMOS33 [get_ports CI_READIN]
set_property IOSTANDARD LVCMOS33 [get_ports CI_CLK_SR]
set_property IOSTANDARD LVCMOS33 [get_ports CI_CLK_READ]
set_property IOSTANDARD LVCMOS33 [get_ports CI_LOAD_SC]
set_property IOSTANDARD LVCMOS33 [get_ports CI_SELECT]
set_property IOSTANDARD LVCMOS33 [get_ports CI_SROUT]
set_property IOSTANDARD LVCMOS33 [get_ports CI_READOUT]

set_property IOSTANDARD LVCMOS33 [get_ports CI_HOLD_HG]
set_property IOSTANDARD LVCMOS33 [get_ports CI_HOLD_LG]
set_property IOSTANDARD LVCMOS33 [get_ports CI_MODEB_EXT]
set_property IOSTANDARD LVCMOS33 [get_ports CI_PS_GTRIG]
set_property IOSTANDARD LVCMOS33 [get_ports CI_VEVT]
set_property IOSTANDARD LVCMOS33 [get_ports CI_RAZCHN]

set_property IOSTANDARD LVCMOS33 [get_ports {PMUX_A[*]}]

# CITIROC trigger ------------------------------------------------------
set_property IOSTANDARD LVCMOS18 [get_ports {CI_TRIGB[*]}]

# DDR3 SDRAM -----------------------------------------------------------
# AD9220 ---------------------------------------------------------------
set_property IOSTANDARD LVCMOS33 [get_ports ADC_OTR]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_BIT[*]]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_CLK]
